TO --escalate=/usr/bin/sudo localhost

RUN env > /tmp/test-env
RUN stat /tmp/test-env
RUN rm /tmp/test-env
RUN stat /tmp/test-env || echo success

COPY Containerfile /tmp/test-file
RUN stat /tmp/test-file
RUN ["rm", "/tmp/test-file"]
RUN stat /tmp/test-file || echo success

COPY Container* /tmp/TargetGlob
RUN stat /tmp/TargetGlob
RUN rm /tmp/TargetGlob
RUN stat /tmp/TargetGlob || echo success

COPY --chown=root:root Containerfile /tmp/
RUN ls -al /tmp/Containerfile | grep "root root"
RUN rm /tmp/Containerfile
RUN stat /tmp/Containerfile || echo success

WORKDIR /tmp
